#!/bin/sh
set -u

printerr() {>&2 printf '%s\n' "$0: $1" ; exit 1; }
usage="-k|-s"

flags=''
while getopts ks f; do
    flags="$flags$f"
done
shift $(expr $OPTIND - 1)
[ $# -gt 0 ] && printerr "$usage"

case "$flags" in
s)  username=$(shuf -n 10 -r -i 0-9 | tr -d '\n')
    domain=$(shuf -n 1 -e com net org)
    printf '%s@1secmail.%s\n' "$username" "$domain"
    ;;
k)  kiwi_url="https://burner.kiwi/api/v1"
    inbox_details=$(curl -fsL "$kiwi_url"/inbox)
    if [ $? != 0 ] ; then
        printerr "curl error"
    fi
    errors=$(printf %s "$inbox_details" | jq -r .errors)
    if [ "$errors" != null ]; then
        printerr "problem creating inbox with kiwi, errors = $errors"
        exit 1
    fi
    printf "%s\n" "$inbox_details"
    ;;
*)  printerr "$usage"
    ;;
esac
