.Dd 2020-10-17
.Dt TEC-CREATE-ADDRESS 1
.Os
.Sh NAME
.Nm tec-create-address
.Nd temporary email commands: create an email address
.Sh SYNOPSIS
.Nm
.Fl k | Fl s
.Sh DESCRIPTION
.Nm
creates an email address for use with a temporary email service.
.Ss Arguments and Options
.Nm
does not take any arguments.
.Bl -tag -width Ds
.It Fl k
Use burner.kiwi temporary email service.  With this option, it prints a json string containing all the details of the account including the authentication token.
.It Fl s
Use 1secmail temporary email service.  With this option, it generates a random email address, which it prints to stdout (without communicating with the service).
.El
.Sh EXAMPLES
.Ss burner.kiwi
Create an email address with burner.kiwi and save the account information:
.Dl tec-create-address -k > kiwi-account.json
.Pp
Show the email address that was created:
.Dl jq -r '.result.email.address' kiwi-account.json
.Pp
Pretty print all the account information:
.Dl jq '' kiwi-account.json
.Ss 1secmail
Generate a random email address for 1secmail and save it:
.Dl tec-create-address -s > secmail-address.txt
.Pp
Show the email address that was generated:
.Dl cat secmail-address.txt
.Sh SEE ALSO
.Xr tec-list-headers 1 , Xr tec-view-message 1 , Xr jq 1
.Pp
.Lk https://burner.kiwi/ ,
.Lk https://www.1secmail.com/
